---
- name: Install PHP
  apt:
    name: php7.1-cli
    state: present

- name: Install PHP7.1-FPM
  apt:
    name: php7.1-fpm
    state: present

- name: Include Debian Vars
  include_vars: Debian.yml

- name: Install other packages
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ phpfpm_pkgs }}'

- name: Install PECL packages
  shell: "yes '' | pecl install {{ item }}"
  with_items: '{{ phpfpm_pkgs_pecl }}'
  register: pecl_result
  changed_when: "not 'is already installed and is the same as the released version' in pecl_result.stdout"
  failed_when: "'No valid packages found' in pecl_result.stdout"

- name: Enable PHP modules
  shell: 'php7.1enmod {{ item }}'
  with_items: '{{ phpfpm_modules_enable }}'

- name: Enable PHP modules
  copy:
    src: '/etc/php7.1/mods-available/{{ item }}.ini'
    dest: '/etc/php7.1/fpm/conf.d/{{ item }}.ini'
  with_items: '{{ phpfpm_modules_enable }}'
